name: Update GitHub Secret with API Value

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  update_secret:
    name: Update Repository Secret
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Read Existing Secret Value
      - name: Read Existing Secret
        env:
          SECRET_VALUE: ${{ secrets.MY_SECRET }}
        run: |
          echo "Current Secret Value: $SECRET_VALUE"

      # Step 3: Fetch New Value from API
      - name: Fetch Random Joke from API
        id: fetch_api
        run: |
          # Fetch data from the jokes API
          RESPONSE=$(curl -s -H "Accept: application/json" https://icanhazdadjoke.com/)
          echo "API Response: $RESPONSE"

          # Extract the joke
          NEW_SECRET=$(echo "$RESPONSE" | jq -r '.joke')
          echo "Fetched New Value: $NEW_SECRET"

          # Save the new secret to environment variables
          echo "NEW_SECRET=$NEW_SECRET" >> $GITHUB_ENV

      # Step 4: Fetch Public Key for Encryption
      - name: Get Repository Public Key
        id: fetch_key
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RESPONSE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/actions/secrets/public-key)

          echo "Public Key Response: $RESPONSE"

          # Extract key and key_id
          echo "key=$(echo $RESPONSE | jq -r '.key')" >> $GITHUB_ENV
          echo "key_id=$(echo $RESPONSE | jq -r '.key_id')" >> $GITHUB_ENV

      # Step 5: Encrypt New Secret Value
      - name: Encrypt New Secret
        id: encrypt_secret
        run: |
          echo "$NEW_SECRET" | openssl rsautl -encrypt -pubin -inkey <(echo "$key" | base64 -d) | base64 -w 0 > encrypted_value.txt
          echo "encrypted_value=$(cat encrypted_value.txt)" >> $GITHUB_ENV

      # Step 6: Update the Secret in the Repository
      - name: Update GitHub Secret
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X PUT \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "encrypted_value": "'"$(cat encrypted_value.txt)"'",
              "key_id": "'"$key_id"'"
            }' \
            https://api.github.com/repos/${{ github.repository }}/actions/secrets/MY_SECRET
