name: Update Github Secret

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  publish:
    name: Publish Image
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Read Secret
        id: api_call
        env:
          SECRET_VALUE: ${{ secrets.MY_SECRET_VALUE }}
        run: |
          echo "Current Secret Value: $SECRET_VALUE"

          # Fetch a new joke using the API
          RESPONSE=$(curl -H "Accept: application/json" https://icanhazdadjoke.com/ || echo '{"joke": "No joke found!"}')
          
          # Extract the joke
          NEW_VALUE=$(echo "$RESPONSE" | jq -r '.joke')

          echo "Fetched New Value: $NEW_VALUE"

          # Save the new value for later use
          echo "new_secret_value=$NEW_VALUE" >> $GITHUB_ENV

      - name: Fetch Repository Public Key
        id: fetch_key
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RESPONSE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/actions/secrets/public-key)
          
          PUBLIC_KEY=$(echo $RESPONSE | jq -r '.key')
          KEY_ID=$(echo $RESPONSE | jq -r '.key_id')

          if [[ -z "$PUBLIC_KEY" || -z "$KEY_ID" ]]; then
            echo "Failed to fetch public key or key ID"
            exit 1
          fi

          echo "key=$PUBLIC_KEY" >> $GITHUB_ENV
          echo "key_id=$KEY_ID" >> $GITHUB_ENV

      - name: Encrypt New Secret Value
        id: encrypt_value
        run: |
          echo "${{ env.new_secret_value }}" | openssl rsautl -encrypt -pubin -inkey <(echo "${{ env.key }}" | base64 -d) | base64 -w 0 > encrypted_value.txt
          echo "encrypted_value=$(cat encrypted_value.txt)" >> $GITHUB_ENV

      - name: Update Github Secret
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          ENCRYPTED_VALUE: ${{ env.encrypted_value }}
          KEY_ID: ${{ env.key_id }}
        run: |
          curl -X PUT \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "encrypted_value": "'"$ENCRYPTED_VALUE"'",
              "key_id": "'"$KEY_ID"'"
            }' \
            https://api.github.com/repos/$REPO/actions/secrets/MY_SECRET_VALUE